"""Walk-forward validation harness.

See CLAUDE.md's "Strategy Research Operational Design" section,
"Walk-forward harness" subsection, for the full design this module
implements.

Rolling (fixed-size sliding, not expanding), non-overlapping-by-default
(`step_bars == validate_bars`) train/validate folds, generated by pure
bar-count arithmetic against the ordered kline sequence -- never calendar-
date splitting. For each fold: `strategy.fit(train_klines, params)` binds
a plain `Strategy`, which is then scored by calling the *existing*,
already lookahead-safety-tested `backtest.engine.run_backtest` against
`validate_klines` -- deliberately not a custom evaluation loop, so every
strategy (rule-based now, ML later) is scored through the one code path
already proven safe against lookahead bias, rather than allowing a
strategy-specific evaluation loop to bypass it.

`run_walk_forward` calls `research.experiment_log.log_run` as its last
action, unconditionally -- including when zero folds are produced (a
too-short kline sequence for the requested window sizes is a legitimate,
loggable outcome, not an error) -- so every call to this function leaves
an audit trail a caller cannot forget to write.

This module deliberately does **not** evaluate CLAUDE.md's Eligibility
Bar (positive Sharpe in every fold, 8-10 fold credibility floor, drawdown
ceiling, minimum trade count, profit factor floor) -- it only computes
and logs the aggregate figures a later evaluator needs. See
`.planning/sr-c-walkforward-holdout.md` for why: the real BingX depth
(~24,199 bars as of Task A's 2026-07-25/26 run) only supports 5 non-
overlapping folds at the provisional default window sizes, short of the
8-10 floor -- a human decision this task flags rather than resolves.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, Callable, Mapping, Protocol, Sequence
from uuid import uuid4

from backtest.engine import BacktestResult, Strategy, run_backtest
from backtest.kline import Kline
from metrics.metrics import Metrics, compute_metrics
from research import experiment_log
from research.robustness import DEFAULT_PERTURBATION_FRACTIONS, check_parameter_sensitivity

# Mark-to-market starting equity for each fold's independent evaluation.
# Folds are scored independently (not as one continuous equity curve
# across the whole run), so this is an arbitrary but fixed reference
# value -- CLAUDE.md's Eligibility Bar is expressed in ratios (Sharpe,
# drawdown %, profit factor) that don't depend on its actual magnitude.
_DEFAULT_STARTING_EQUITY = Decimal("10000")

# Default Sharpe-annualization bars-per-day, matching
# `metrics.metrics`'s own default -- every 15m caller (every strategy in
# this project before Strategy Research Task F) omits `bars_per_day` and
# sees identical behavior to before this parameter existed. See
# `metrics/metrics.py`'s `_BARS_PER_DAY` comment and `.planning/sr-f-risk-
# management-and-1h-variant.md` for why this became a parameter (the
# native-1h strategy variant needs 24, not 96, or its reported Sharpe is
# silently inflated 2x).
_DEFAULT_BARS_PER_DAY = 96


class TrainableStrategy(Protocol):
    def fit(self, train_klines: list[Kline], params: Mapping[str, Any], *, parent_run_id: str) -> Strategy:
        """Return a bar-by-bar `Strategy` bound to `params`, trained only
        on `train_klines`. Must not read `validate_klines` in any way --
        it isn't passed to `fit()`, structurally the same "can't see
        what it shouldn't" guarantee `KlineWindow` gives `run_backtest`'s
        bar loop.

        `parent_run_id` is this call's own `run_walk_forward` invocation's
        `run_id` -- generated once, before the fold loop starts, so every
        fold's `fit()` call receives the same value (see
        `run_walk_forward`'s docstring). It exists purely so a `fit()`
        implementation that wants to log its own sub-run detail (e.g. a
        grid search logging each candidate's own train-only backtest as
        its own `backtest_run` entry) has a correct `parent_run_id` to
        attach those records to, via `research.experiment_log.log_run`'s
        `parent_run_id`/`candidate_index`/`total_candidates` fields --
        see CLAUDE.md's Strategy Research Operational Design, "Build
        sequencing" (Task D), and `python/research/strategies/
        ma_crossover.py` for the concrete example. A `fit()`
        implementation with nothing of its own to log may simply ignore
        this parameter.
        """
        ...


@dataclass(frozen=True)
class Fold:
    """One rolling train/validate window, expressed purely as bar
    indices into the ordered kline sequence passed to `generate_folds`/
    `run_walk_forward`. `*_end_index` values are exclusive (half-open),
    matching this codebase's existing `[start, end)` convention (see
    `data/_grid.py`).
    """

    fold_index: int
    train_start_index: int
    train_end_index: int
    validate_start_index: int
    validate_end_index: int


@dataclass(frozen=True)
class FoldResult:
    """A `Fold`'s boundaries flattened alongside its evaluation output --
    kept as one flat record (rather than `Fold` nested under a `.fold`
    attribute) so a caller can read `fold_result.train_start_index`
    directly instead of `fold_result.fold.train_start_index`.
    """

    fold_index: int
    train_start_index: int
    train_end_index: int
    validate_start_index: int
    validate_end_index: int
    metrics: Metrics
    backtest_result: BacktestResult
    parameter_sensitivity: dict | None = None


@dataclass(frozen=True)
class WalkForwardResult:
    run_id: str
    strategy_id: str
    strategy_version: str
    params: dict
    folds: list[FoldResult] = field(default_factory=list)
    aggregate: dict = field(default_factory=dict)


def generate_folds(n_bars: int, train_bars: int, validate_bars: int, step_bars: int) -> list[Fold]:
    """Generate rolling train/validate fold boundaries by pure bar-count
    arithmetic. `step_bars == validate_bars` (the documented default)
    produces non-overlapping, contiguous validate windows; a smaller
    `step_bars` produces overlapping validate windows -- this function
    works correctly and generically for whatever window/step sizes are
    passed, never hardcoding an assumption about how many folds result.

    Returns an empty list if `n_bars` is too small to fit even one full
    train+validate window -- a legitimate, non-error outcome (see module
    docstring).
    """
    if train_bars <= 0:
        raise ValueError(f"train_bars must be positive, got {train_bars}")
    if validate_bars <= 0:
        raise ValueError(f"validate_bars must be positive, got {validate_bars}")
    if step_bars <= 0:
        raise ValueError(f"step_bars must be positive, got {step_bars}")

    folds: list[Fold] = []
    train_start = 0
    fold_index = 0
    while True:
        train_end = train_start + train_bars
        validate_end = train_end + validate_bars
        if validate_end > n_bars:
            break
        folds.append(
            Fold(
                fold_index=fold_index,
                train_start_index=train_start,
                train_end_index=train_end,
                validate_start_index=train_end,
                validate_end_index=validate_end,
            )
        )
        fold_index += 1
        train_start += step_bars

    return folds


def run_walk_forward(
    klines: list[Kline],
    strategy: TrainableStrategy,
    strategy_id: str,
    strategy_version: str,
    params: Mapping[str, Any],
    *,
    train_bars: int,
    validate_bars: int,
    step_bars: int,
    fee_bps: Decimal,
    slippage_bps: Decimal,
    starting_equity: Decimal = _DEFAULT_STARTING_EQUITY,
    bars_per_day: int = _DEFAULT_BARS_PER_DAY,
    is_holdout_run: bool = False,
    parent_run_id: str | None = None,
    candidate_index: int | None = None,
    total_candidates: int | None = None,
    sensitivity_extractor: Callable[[Strategy], Sequence[int]] | None = None,
    sensitivity_fractions: Sequence[Decimal] = DEFAULT_PERTURBATION_FRACTIONS,
    runs_path: str = experiment_log.DEFAULT_RUNS_PATH,
) -> WalkForwardResult:
    """Run one walk-forward validation pass and log it.

    For each fold: `strategy.fit(train_klines, params, parent_run_id=...)`
    binds a `Strategy` seeing only that fold's train window, then
    `backtest.engine.run_backtest` evaluates it against that fold's
    validate window -- the one code path already proven lookahead-safe.
    Each fold's `BacktestResult` is reduced to a `Metrics` record via
    `metrics.metrics.compute_metrics`.

    This run's own `run_id` is generated once, up front -- before the
    fold loop begins -- specifically so it can be passed to every fold's
    `strategy.fit()` call as `parent_run_id` (see `TrainableStrategy.fit`'s
    docstring for why: a `fit()` implementation that wants to log its own
    sub-run detail, e.g. a grid search's per-candidate backtests, needs a
    correct parent run id to attach those records to, and the only run id
    that legitimately identifies *this* `run_walk_forward` call is the one
    it will itself log under -- so it must exist before any `fit()` call
    happens, not just at the end when this function logs its own record).

    Calls `research.experiment_log.log_run` as its last action,
    unconditionally -- including for zero folds -- so every call leaves
    an audit-trail entry a caller cannot skip. `is_holdout_run`,
    `parent_run_id`, `candidate_index`, `total_candidates` are passed
    straight through to `log_run`; `parent_run_id`/`candidate_index`/
    `total_candidates` are for Task D's grid search (`None` for a
    standalone run, which is every call this task makes).

    `train_bars`/`validate_bars`/`step_bars`/`fee_bps`/`slippage_bps` are
    keyword-only, unlike CLAUDE.md's Build-section signature snippet
    (which lists them positionally) -- a deliberate, zero-cost deviation:
    five adjacent same-typed parameters (three bare `int`s, then two
    `Decimal`s) are exactly the shape a transposed-argument bug hides in,
    and every call site in this codebase already passes them by keyword.
    See `.planning/sr-c-walkforward-holdout.md`.

    `sensitivity_extractor` (default `None` -- purely additive, every
    existing caller is unaffected) opts a fold into the parameter-
    sensitivity overfitting check (`research.robustness.
    check_parameter_sensitivity`, see `.planning/sr-g-overfitting-
    safeguards.md`, "Finding 2"): a callable that, given the `Strategy`
    `strategy.fit()` just returned for a fold, extracts the winning
    candidate tuple that strategy was bound to (e.g. `lambda s: (s.
    fast_window, s.slow_window)` for `ma_crossover`/`regime_momentum`-
    shaped strategies, which already expose these as properties). When
    given, every fold's `FoldResult.parameter_sensitivity` (and the
    corresponding logged record's `fold_results[i]["parameter_sensitivity"]`)
    is populated with `check_parameter_sensitivity(...).to_dict()`,
    evaluated against that same fold's `train_klines` (never
    `validate_klines`); when omitted, `parameter_sensitivity` stays `None`
    and is omitted from the logged record entirely, so an existing reader
    of `runs/experiments.jsonl` sees byte-for-byte the same shape as
    before this parameter existed. `sensitivity_fractions` is passed
    straight through to `check_parameter_sensitivity`'s `fractions`
    parameter (default +-10%/+-25%, per that module's own default).
    """
    if fee_bps < 0:
        raise ValueError(f"fee_bps must be non-negative, got {fee_bps}")
    if slippage_bps < 0:
        raise ValueError(f"slippage_bps must be non-negative, got {slippage_bps}")

    folds = generate_folds(len(klines), train_bars, validate_bars, step_bars)

    # Generated here, before the fold loop, not after it -- see this
    # function's docstring and `TrainableStrategy.fit`'s docstring for why:
    # every fold's `fit()` call below needs this run's own id as
    # `parent_run_id`, so it must exist before the first `fit()` call, not
    # only once the loop has already finished.
    run_id = str(uuid4())

    fold_results: list[FoldResult] = []
    for fold in folds:
        train_klines = klines[fold.train_start_index : fold.train_end_index]
        validate_klines = klines[fold.validate_start_index : fold.validate_end_index]

        bound_strategy = strategy.fit(train_klines, params, parent_run_id=run_id)
        backtest_result = run_backtest(validate_klines, bound_strategy, fee_bps, slippage_bps)
        fold_metrics = compute_metrics(
            validate_klines,
            backtest_result.filled_intents,
            backtest_result.fills,
            starting_equity,
            bars_per_day=bars_per_day,
        )

        parameter_sensitivity: dict | None = None
        if sensitivity_extractor is not None:
            winning_candidate = sensitivity_extractor(bound_strategy)
            sensitivity_result = check_parameter_sensitivity(
                strategy,
                params,
                winning_candidate,
                train_klines,
                fee_bps=fee_bps,
                slippage_bps=slippage_bps,
                starting_equity=starting_equity,
                bars_per_day=bars_per_day,
                fractions=sensitivity_fractions,
                # Deliberately NOT this fold's run_id: check_parameter_
                # sensitivity's own docstring explains why passing the
                # real grid search's own parent_run_id here would corrupt
                # research.overfitting_check's MinBTL-style counting (it
                # groups by parent_run_id and expects one consistent
                # total_candidates per group -- mixing in a batch of
                # single-candidate sensitivity fit() calls under the same
                # id breaks that assumption). Leaving this at its default
                # (None) makes every sensitivity-driven fit() call log as
                # its own standalone record instead.
            )
            parameter_sensitivity = sensitivity_result.to_dict()

        fold_results.append(
            FoldResult(
                fold_index=fold.fold_index,
                train_start_index=fold.train_start_index,
                train_end_index=fold.train_end_index,
                validate_start_index=fold.validate_start_index,
                validate_end_index=fold.validate_end_index,
                metrics=fold_metrics,
                backtest_result=backtest_result,
                parameter_sensitivity=parameter_sensitivity,
            )
        )

    aggregate = _aggregate_metrics(fold_results)

    experiment_log.log_run(
        run_id=run_id,
        strategy_id=strategy_id,
        strategy_version=strategy_version,
        params=params,
        fold_results=[_fold_result_to_log_dict(fr) for fr in fold_results],
        aggregate_metrics=aggregate,
        data_range=_data_range(klines),
        walk_forward_config={
            "train_bars": train_bars,
            "validate_bars": validate_bars,
            "step_bars": step_bars,
            "fold_count": len(fold_results),
        },
        fee_bps=fee_bps,
        slippage_bps=slippage_bps,
        is_holdout_run=is_holdout_run,
        parent_run_id=parent_run_id,
        candidate_index=candidate_index,
        total_candidates=total_candidates,
        runs_path=runs_path,
    )

    return WalkForwardResult(
        run_id=run_id,
        strategy_id=strategy_id,
        strategy_version=strategy_version,
        params=dict(params),
        folds=fold_results,
        aggregate=aggregate,
    )


def _data_range(klines: list[Kline]) -> dict:
    if not klines:
        return {"start_ms": None, "end_ms": None, "num_bars": 0}
    return {
        "start_ms": int(klines[0].open_time.timestamp() * 1000),
        "end_ms": int(klines[-1].open_time.timestamp() * 1000),
        "num_bars": len(klines),
    }


def _metrics_summary(metrics: Metrics) -> dict:
    """Scalar-only summary of a fold's `Metrics` -- deliberately omits
    `equity_curve`/`closed_trades` (the two genuinely large fields) from
    what gets persisted to `runs/experiments.jsonl`. The full `Metrics`
    (including both) stays available in the in-memory `WalkForwardResult`
    for any caller that needs it (e.g. Task D's grid search comparing
    candidates); the persisted log only needs the numbers CLAUDE.md's
    Eligibility Bar is expressed in terms of.
    """
    return {
        "starting_equity": metrics.starting_equity,
        "final_equity": metrics.final_equity,
        "total_return": metrics.total_return,
        "sharpe_ratio": metrics.sharpe_ratio,
        "max_drawdown": metrics.max_drawdown,
        "win_rate": metrics.win_rate,
        "num_trades": metrics.num_trades,
        "profit_factor": metrics.profit_factor,
    }


def _fold_result_to_log_dict(fold_result: FoldResult) -> dict:
    record = {
        "fold_index": fold_result.fold_index,
        "train_start_index": fold_result.train_start_index,
        "train_end_index": fold_result.train_end_index,
        "validate_start_index": fold_result.validate_start_index,
        "validate_end_index": fold_result.validate_end_index,
        "metrics": _metrics_summary(fold_result.metrics),
    }
    # Additive -- only present when a caller opted in via
    # run_walk_forward's sensitivity_extractor parameter, so an existing
    # reader of runs/experiments.jsonl sees byte-for-byte the same fold
    # record shape as before this field existed. See run_walk_forward's
    # docstring and .planning/sr-g-overfitting-safeguards.md ("Finding 2").
    if fold_result.parameter_sensitivity is not None:
        record["parameter_sensitivity"] = fold_result.parameter_sensitivity
    return record


def _aggregate_metrics(fold_results: list[FoldResult]) -> dict:
    """Reduce per-fold `Metrics` to the aggregate figures CLAUDE.md's
    Eligibility Bar is evaluated against later -- evaluating the bar
    itself is explicitly not this function's job (see module docstring).

    `None`-not-zero-not-inf propagation matches `metrics.metrics`'s own
    degenerate-input philosophy throughout: a fold with a `None` Sharpe
    (zero trades or zero-variance returns) is excluded from `mean_sharpe`/
    `min_sharpe` (no evidence to average in) but *does* count against
    `all_folds_positive_sharpe` (a `None` fold trivially fails "positive
    in every fold"). Same pattern for `profit_factor`.
    """
    fold_count = len(fold_results)
    if fold_count == 0:
        return {
            "fold_count": 0,
            "mean_sharpe": None,
            "min_sharpe": None,
            "all_folds_positive_sharpe": False,
            "worst_fold_max_drawdown": None,
            "mean_total_return": None,
            "total_trades": 0,
            "mean_profit_factor": None,
            "min_profit_factor": None,
            "folds_with_zero_trades": 0,
        }

    sharpe_values = [fr.metrics.sharpe_ratio for fr in fold_results]
    defined_sharpe_values = [s for s in sharpe_values if s is not None]
    profit_factors = [fr.metrics.profit_factor for fr in fold_results]
    defined_profit_factors = [p for p in profit_factors if p is not None]

    return {
        "fold_count": fold_count,
        "mean_sharpe": (sum(defined_sharpe_values) / len(defined_sharpe_values)) if defined_sharpe_values else None,
        "min_sharpe": min(defined_sharpe_values) if defined_sharpe_values else None,
        "all_folds_positive_sharpe": all(s is not None and s > 0 for s in sharpe_values),
        "worst_fold_max_drawdown": max(fr.metrics.max_drawdown for fr in fold_results),
        "mean_total_return": sum((fr.metrics.total_return for fr in fold_results), Decimal(0)) / fold_count,
        "total_trades": sum(fr.metrics.num_trades for fr in fold_results),
        "mean_profit_factor": (
            (sum(defined_profit_factors) / len(defined_profit_factors)) if defined_profit_factors else None
        ),
        "min_profit_factor": min(defined_profit_factors) if defined_profit_factors else None,
        "folds_with_zero_trades": sum(1 for fr in fold_results if fr.metrics.num_trades == 0),
    }
