"""Walk-forward validation harness.

See CLAUDE.md's "Strategy Research Operational Design" section,
"Walk-forward harness" subsection, for the full design this module
implements.

Rolling (fixed-size sliding, not expanding), non-overlapping-by-default
(`step_bars == validate_bars`) train/validate folds, generated by pure
bar-count arithmetic against the ordered kline sequence -- never calendar-
date splitting. For each fold: `strategy.fit(train_klines, params)` binds
a plain `Strategy`, which is then scored by calling the *existing*,
already lookahead-safety-tested `backtest.engine.run_backtest` against
`validate_klines` -- deliberately not a custom evaluation loop, so every
strategy (rule-based now, ML later) is scored through the one code path
already proven safe against lookahead bias, rather than allowing a
strategy-specific evaluation loop to bypass it.

`run_walk_forward` calls `research.experiment_log.log_run` as its last
action, unconditionally -- including when zero folds are produced (a
too-short kline sequence for the requested window sizes is a legitimate,
loggable outcome, not an error) -- so every call to this function leaves
an audit trail a caller cannot forget to write.

This module deliberately does **not** evaluate CLAUDE.md's Eligibility
Bar (positive Sharpe in every fold, 8-10 fold credibility floor, drawdown
ceiling, minimum trade count, profit factor floor) -- it only computes
and logs the aggregate figures a later evaluator needs. See
`.planning/sr-c-walkforward-holdout.md` for why: the real BingX depth
(~24,199 bars as of Task A's 2026-07-25/26 run) only supports 5 non-
overlapping folds at the provisional default window sizes, short of the
8-10 floor -- a human decision this task flags rather than resolves.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, Callable, Mapping, Protocol, Sequence
from uuid import uuid4

from backtest.engine import BacktestResult, Strategy, run_backtest
from backtest.kline import Kline
from metrics.funding import FundingRate
from metrics.metrics import Metrics, compute_metrics
from research import experiment_log
from research.overfitting_check import SENSITIVITY_PARENT_RUN_ID_PREFIX
from research.robustness import DEFAULT_PERTURBATION_FRACTIONS, check_parameter_sensitivity

# Mark-to-market starting equity for each fold's independent evaluation.
# Folds are scored independently (not as one continuous equity curve
# across the whole run), so this is an arbitrary but fixed reference
# value -- CLAUDE.md's Eligibility Bar is expressed in ratios (Sharpe,
# drawdown %, profit factor) that don't depend on its actual magnitude.
_DEFAULT_STARTING_EQUITY = Decimal("10000")

# Default Sharpe-annualization bars-per-day, matching
# `metrics.metrics`'s own default -- every 15m caller (every strategy in
# this project before Strategy Research Task F) omits `bars_per_day` and
# sees identical behavior to before this parameter existed. See
# `metrics/metrics.py`'s `_BARS_PER_DAY` comment and `.planning/sr-f-risk-
# management-and-1h-variant.md` for why this became a parameter (the
# native-1h strategy variant needs 24, not 96, or its reported Sharpe is
# silently inflated 2x).
_DEFAULT_BARS_PER_DAY = 96


class TrainableStrategy(Protocol):
    def fit(self, train_klines: list[Kline], params: Mapping[str, Any], *, parent_run_id: str) -> Strategy:
        """Return a bar-by-bar `Strategy` bound to `params`, trained only
        on `train_klines`. Must not read `validate_klines` in any way --
        it isn't passed to `fit()`, structurally the same "can't see
        what it shouldn't" guarantee `KlineWindow` gives `run_backtest`'s
        bar loop.

        `parent_run_id` is this call's own `run_walk_forward` invocation's
        `run_id` -- generated once, before the fold loop starts, so every
        fold's `fit()` call receives the same value (see
        `run_walk_forward`'s docstring). It exists purely so a `fit()`
        implementation that wants to log its own sub-run detail (e.g. a
        grid search logging each candidate's own train-only backtest as
        its own `backtest_run` entry) has a correct `parent_run_id` to
        attach those records to, via `research.experiment_log.log_run`'s
        `parent_run_id`/`candidate_index`/`total_candidates` fields --
        see CLAUDE.md's Strategy Research Operational Design, "Build
        sequencing" (Task D), and `python/research/strategies/
        ma_crossover.py` for the concrete example. A `fit()`
        implementation with nothing of its own to log may simply ignore
        this parameter.
        """
        ...


@dataclass(frozen=True)
class Fold:
    """One rolling train/validate window, expressed purely as bar
    indices into the ordered kline sequence passed to `generate_folds`/
    `run_walk_forward`. `*_end_index` values are exclusive (half-open),
    matching this codebase's existing `[start, end)` convention (see
    `data/_grid.py`).
    """

    fold_index: int
    train_start_index: int
    train_end_index: int
    validate_start_index: int
    validate_end_index: int


@dataclass(frozen=True)
class FoldResult:
    """A `Fold`'s boundaries flattened alongside its evaluation output --
    kept as one flat record (rather than `Fold` nested under a `.fold`
    attribute) so a caller can read `fold_result.train_start_index`
    directly instead of `fold_result.fold.train_start_index`.
    """

    fold_index: int
    train_start_index: int
    train_end_index: int
    validate_start_index: int
    validate_end_index: int
    metrics: Metrics
    backtest_result: BacktestResult
    parameter_sensitivity: dict | None = None


@dataclass(frozen=True)
class WalkForwardResult:
    run_id: str
    strategy_id: str
    strategy_version: str
    params: dict
    folds: list[FoldResult] = field(default_factory=list)
    aggregate: dict = field(default_factory=dict)


def generate_folds(n_bars: int, train_bars: int, validate_bars: int, step_bars: int) -> list[Fold]:
    """Generate rolling train/validate fold boundaries by pure bar-count
    arithmetic. `step_bars == validate_bars` (the documented default)
    produces non-overlapping, contiguous validate windows; a smaller
    `step_bars` produces overlapping validate windows -- this function
    works correctly and generically for whatever window/step sizes are
    passed, never hardcoding an assumption about how many folds result.

    Returns an empty list if `n_bars` is too small to fit even one full
    train+validate window -- a legitimate, non-error outcome (see module
    docstring).
    """
    if train_bars <= 0:
        raise ValueError(f"train_bars must be positive, got {train_bars}")
    if validate_bars <= 0:
        raise ValueError(f"validate_bars must be positive, got {validate_bars}")
    if step_bars <= 0:
        raise ValueError(f"step_bars must be positive, got {step_bars}")

    folds: list[Fold] = []
    train_start = 0
    fold_index = 0
    while True:
        train_end = train_start + train_bars
        validate_end = train_end + validate_bars
        if validate_end > n_bars:
            break
        folds.append(
            Fold(
                fold_index=fold_index,
                train_start_index=train_start,
                train_end_index=train_end,
                validate_start_index=train_end,
                validate_end_index=validate_end,
            )
        )
        fold_index += 1
        train_start += step_bars

    return folds


def run_walk_forward(
    klines: list[Kline],
    strategy: TrainableStrategy,
    strategy_id: str,
    strategy_version: str,
    params: Mapping[str, Any],
    *,
    train_bars: int,
    validate_bars: int,
    step_bars: int,
    fee_bps: Decimal,
    slippage_bps: Decimal,
    starting_equity: Decimal = _DEFAULT_STARTING_EQUITY,
    bars_per_day: int = _DEFAULT_BARS_PER_DAY,
    funding_rates: Sequence[FundingRate] | None = None,
    is_holdout_run: bool = False,
    parent_run_id: str | None = None,
    candidate_index: int | None = None,
    total_candidates: int | None = None,
    strategy_family: str | None = None,
    preregistration_id: str | None = None,
    preregistration_sha256: str | None = None,
    sensitivity_extractor: Callable[[Strategy], Sequence[int]] | None = None,
    sensitivity_fractions: Sequence[Decimal] = DEFAULT_PERTURBATION_FRACTIONS,
    runs_path: str = experiment_log.DEFAULT_RUNS_PATH,
) -> WalkForwardResult:
    """Run one walk-forward validation pass and log it.

    For each fold: `strategy.fit(train_klines, params, parent_run_id=...)`
    binds a `Strategy` seeing only that fold's train window, then
    `backtest.engine.run_backtest` evaluates it against that fold's
    validate window -- the one code path already proven lookahead-safe.
    Each fold's `BacktestResult` is reduced to a `Metrics` record via
    `metrics.metrics.compute_metrics`.

    This run's own `run_id` is generated once, up front -- before the
    fold loop begins -- specifically so it can be passed to every fold's
    `strategy.fit()` call as `parent_run_id` (see `TrainableStrategy.fit`'s
    docstring for why: a `fit()` implementation that wants to log its own
    sub-run detail, e.g. a grid search's per-candidate backtests, needs a
    correct parent run id to attach those records to, and the only run id
    that legitimately identifies *this* `run_walk_forward` call is the one
    it will itself log under -- so it must exist before any `fit()` call
    happens, not just at the end when this function logs its own record).

    Calls `research.experiment_log.log_run` as its last action,
    unconditionally -- including for zero folds -- so every call leaves
    an audit-trail entry a caller cannot skip. `is_holdout_run`,
    `parent_run_id`, `candidate_index`, `total_candidates` are passed
    straight through to `log_run`; `parent_run_id`/`candidate_index`/
    `total_candidates` are for Task D's grid search (`None` for a
    standalone run, which is every call this task makes).

    `strategy_family` (default `None` -- purely additive, Strategy
    Research Task P) is passed straight through to `log_run`, which omits
    the key entirely rather than writing `null` when it is `None`; see
    that function's docstring and `research/lineage.py` for why. Supplying
    it makes a run self-describing, so `research.overfitting_check.
    check_project_combination_count` doesn't have to fall back to
    `research.lineage.FAMILY_BY_STRATEGY_ID`'s curated historical map to
    work out which research family the run belongs to.

    `preregistration_id`/`preregistration_sha256` (default `None` -- purely
    additive, Strategy Research Task S) are passed straight through to
    `log_run`, which omits both keys entirely rather than writing `null`
    when they are `None`; see that function's docstring and
    `research/preregistration.py`. They record which committed
    pre-registration a run was made under, and the SHA-256 of that file's
    bytes as read at run time. They must be supplied together or not at
    all, validated at this function's entry point rather than only in
    `log_run` for the same reason as the `bars_per_day` check below:
    `log_run` runs after every fold has already been backtested, so failing
    there would throw away a completed run's results.
    `research/run_preregistered.py` is the intended caller; anything else
    passing them is asserting a provenance claim it should be able to
    substantiate.

    `train_bars`/`validate_bars`/`step_bars`/`fee_bps`/`slippage_bps` are
    keyword-only, unlike CLAUDE.md's Build-section signature snippet
    (which lists them positionally) -- a deliberate, zero-cost deviation:
    five adjacent same-typed parameters (three bare `int`s, then two
    `Decimal`s) are exactly the shape a transposed-argument bug hides in,
    and every call site in this codebase already passes them by keyword.
    See `.planning/sr-c-walkforward-holdout.md`.

    `funding_rates` (default `None` -- purely additive, Strategy Research
    Task N; every existing caller omitting it sees byte-for-byte the same
    fold metrics as before this parameter existed) is passed straight
    through, unfiltered, to every fold's `metrics.metrics.compute_metrics`
    call as its own `funding_rates` argument -- so each fold's reported
    Sharpe/return/drawdown/profit-factor and every `ClosedTrade.realized_
    pnl` reflect real funding P&L, not just price P&L. Passing the SAME
    (typically full-history) series to every fold is deliberate and safe,
    not a lookahead risk: `compute_metrics`/`metrics.position.
    PositionTracker.apply_funding_through` only ever consume funding rows
    up to each kline's own `open_time` (see that module's docstring for
    its cursor-based look-ahead-safety design) -- a fold's own
    `validate_klines` upper bound still caps what actually gets applied,
    regardless of how much extra (temporally later) data the passed-in
    series happens to contain. Not threaded into
    `sensitivity_extractor`/`check_parameter_sensitivity`'s in-sample
    re-evaluations (a diagnostic-only, opt-in add-on with its own already-
    documented failure containment) -- funding P&L for that path is
    deliberately out of scope for this task, see
    `.planning/sr-n-funding-rate-strategy.md`.

    `sensitivity_extractor` (default `None` -- purely additive, every
    existing caller is unaffected) opts a fold into the parameter-
    sensitivity overfitting check (`research.robustness.
    check_parameter_sensitivity`, see `.planning/sr-g-overfitting-
    safeguards.md`, "Finding 2"): a callable that, given the `Strategy`
    `strategy.fit()` just returned for a fold, extracts the winning
    candidate tuple that strategy was bound to (e.g. `lambda s: (s.
    fast_window, s.slow_window)` for `ma_crossover`/`regime_momentum`-
    shaped strategies, which already expose these as properties). When
    given, every fold's `FoldResult.parameter_sensitivity` (and the
    corresponding logged record's `fold_results[i]["parameter_sensitivity"]`)
    is populated with `check_parameter_sensitivity(...).to_dict()`,
    evaluated against that same fold's `train_klines` (never
    `validate_klines`); when omitted, `parameter_sensitivity` stays `None`
    and is omitted from the logged record entirely, so an existing reader
    of `runs/experiments.jsonl` sees byte-for-byte the same shape as
    before this parameter existed. `sensitivity_fractions` is passed
    straight through to `check_parameter_sensitivity`'s `fractions`
    parameter (default +-10%/+-25%, per that module's own default).

    **Failure containment**: `sensitivity_extractor` and
    `check_parameter_sensitivity` are both called inside a broad
    `try/except` -- this whole feature is an optional, diagnostic-only
    add-on, so a bug in a caller-supplied extractor, or
    `check_parameter_sensitivity` itself raising (it explicitly does, by
    design, when the winning candidate can't be re-evaluated -- see its
    own docstring), must never abort the fold loop or skip this
    function's unconditional final `log_run()` call. On failure,
    `parameter_sensitivity` is set to `{"sensitivity_check_error":
    str(exc)}` for that fold instead -- a distinctly different shape from
    a successful `check_parameter_sensitivity(...).to_dict()` result (no
    `winning_candidate`/`is_robust`/`neighbors` keys), so a reader can
    trivially tell the two apart. The fold's own real result (`metrics`,
    `backtest_result`) is entirely unaffected by a sensitivity-check
    failure either way.
    """
    if fee_bps < 0:
        raise ValueError(f"fee_bps must be non-negative, got {fee_bps}")
    if slippage_bps < 0:
        raise ValueError(f"slippage_bps must be non-negative, got {slippage_bps}")
    # Checked here, not left to compute_metrics' own identical check: a run
    # that produces zero folds never calls compute_metrics at all, so an
    # unusable bars_per_day would otherwise be written into
    # walk_forward_config below and logged as a successful run -- a value
    # PSR/DSR then cannot de-annualize with. Same fail-loud-at-the-entry-
    # point convention as the two checks above. (CodeRabbit review finding
    # on PR #52.)
    if bars_per_day <= 0:
        raise ValueError(f"bars_per_day must be positive, got {bars_per_day}")
    # Same "fail at the entry point, not at logging time" reasoning as the
    # check above (Strategy Research Task S): `log_run` enforces this too,
    # but by then every fold has already been backtested.
    experiment_log.require_complete_preregistration_pair(preregistration_id, preregistration_sha256)

    folds = generate_folds(len(klines), train_bars, validate_bars, step_bars)

    # Generated here, before the fold loop, not after it -- see this
    # function's docstring and `TrainableStrategy.fit`'s docstring for why:
    # every fold's `fit()` call below needs this run's own id as
    # `parent_run_id`, so it must exist before the first `fit()` call, not
    # only once the loop has already finished.
    run_id = str(uuid4())

    fold_results: list[FoldResult] = []
    for fold in folds:
        train_klines = klines[fold.train_start_index : fold.train_end_index]
        validate_klines = klines[fold.validate_start_index : fold.validate_end_index]

        bound_strategy = strategy.fit(train_klines, params, parent_run_id=run_id)
        backtest_result = run_backtest(validate_klines, bound_strategy, fee_bps, slippage_bps)
        fold_metrics = compute_metrics(
            validate_klines,
            backtest_result.filled_intents,
            backtest_result.fills,
            starting_equity,
            bars_per_day=bars_per_day,
            funding_rates=funding_rates,
        )

        parameter_sensitivity: dict | None = None
        if sensitivity_extractor is not None:
            # This whole block is an optional, diagnostic-only add-on --
            # per this function's own docstring ("every call to this
            # function leaves an audit trail a caller cannot forget to
            # write"), a bug in the caller-supplied sensitivity_extractor
            # or inside check_parameter_sensitivity itself (e.g. it
            # explicitly re-raises when the winning candidate can't be
            # re-evaluated -- see that function's docstring) must never
            # abort the fold loop or skip the unconditional log_run()
            # call below. Caught broadly and recorded on the fold instead
            # of propagated -- a real gap found by CodeRabbit review, not
            # anticipated in the original design; see
            # .planning/sr-g-overfitting-safeguards.md.
            try:
                winning_candidate = sensitivity_extractor(bound_strategy)
                sensitivity_result = check_parameter_sensitivity(
                    strategy,
                    params,
                    winning_candidate,
                    train_klines,
                    fee_bps=fee_bps,
                    slippage_bps=slippage_bps,
                    starting_equity=starting_equity,
                    bars_per_day=bars_per_day,
                    fractions=sensitivity_fractions,
                    # Deliberately NOT this fold's bare run_id: check_
                    # parameter_sensitivity's own docstring explains why
                    # passing the real grid search's own parent_run_id here
                    # would corrupt research.overfitting_check's MinBTL-style
                    # counting (it groups by parent_run_id and expects one
                    # consistent total_candidates per group -- mixing in a
                    # batch of single-candidate sensitivity fit() calls under
                    # the same id breaks that assumption).
                    #
                    # sr-g's fix for that was to leave this at its default
                    # (None), making every sensitivity-driven fit() log as an
                    # anonymous standalone record. Strategy Research Task P
                    # supersedes that compromise with a PREFIXED DISTINCT id:
                    # it's a different parent_run_id from the real grid's, so
                    # the group-corruption problem sr-g solved stays solved,
                    # and the records are now self-identifying as sensitivity
                    # probes instead of being indistinguishable from real
                    # standalone runs. See .planning/sr-p-trial-accounting.md.
                    parent_run_id=f"{SENSITIVITY_PARENT_RUN_ID_PREFIX}{run_id}",
                )
                parameter_sensitivity = sensitivity_result.to_dict()
            except Exception as exc:  # noqa: BLE001 -- deliberately broad, see comment above
                parameter_sensitivity = {"sensitivity_check_error": str(exc)}

        fold_results.append(
            FoldResult(
                fold_index=fold.fold_index,
                train_start_index=fold.train_start_index,
                train_end_index=fold.train_end_index,
                validate_start_index=fold.validate_start_index,
                validate_end_index=fold.validate_end_index,
                metrics=fold_metrics,
                backtest_result=backtest_result,
                parameter_sensitivity=parameter_sensitivity,
            )
        )

    aggregate = _aggregate_metrics(fold_results)

    walk_forward_config: dict = {
        "train_bars": train_bars,
        "validate_bars": validate_bars,
        "step_bars": step_bars,
        "fold_count": len(fold_results),
        # Unconditional (Strategy Research Task Q). Previously a logged
        # record's timeframe was only inferable by reverse-engineering
        # train_bars (2160 => 1h, 8640 => 15m) -- fragile, and wrong the
        # moment a new window size is used. The Probabilistic/Deflated
        # Sharpe Ratio must de-annualize a logged Sharpe (dividing by
        # sqrt(bars_per_day * 365)), so it needs this exactly, not by
        # inference. Same "always known, so always logged" reasoning as the
        # return moments in _metrics_summary above.
        "bars_per_day": bars_per_day,
    }
    # Additive -- only present when a caller opted in via funding_rates,
    # so an existing reader of runs/experiments.jsonl sees byte-for-byte
    # the same walk_forward_config shape as before this parameter existed
    # (same "field only appears when the feature is actually used"
    # convention as parameter_sensitivity above).
    if funding_rates:
        walk_forward_config["funding_pnl_included"] = True

    experiment_log.log_run(
        run_id=run_id,
        strategy_id=strategy_id,
        strategy_version=strategy_version,
        params=params,
        fold_results=[_fold_result_to_log_dict(fr) for fr in fold_results],
        aggregate_metrics=aggregate,
        data_range=_data_range(klines),
        walk_forward_config=walk_forward_config,
        fee_bps=fee_bps,
        slippage_bps=slippage_bps,
        is_holdout_run=is_holdout_run,
        parent_run_id=parent_run_id,
        candidate_index=candidate_index,
        total_candidates=total_candidates,
        strategy_family=strategy_family,
        preregistration_id=preregistration_id,
        preregistration_sha256=preregistration_sha256,
        runs_path=runs_path,
    )

    return WalkForwardResult(
        run_id=run_id,
        strategy_id=strategy_id,
        strategy_version=strategy_version,
        params=dict(params),
        folds=fold_results,
        aggregate=aggregate,
    )


def _data_range(klines: list[Kline]) -> dict:
    if not klines:
        return {"start_ms": None, "end_ms": None, "num_bars": 0}
    return {
        "start_ms": int(klines[0].open_time.timestamp() * 1000),
        "end_ms": int(klines[-1].open_time.timestamp() * 1000),
        "num_bars": len(klines),
    }


def _metrics_summary(metrics: Metrics) -> dict:
    """Scalar-only summary of a fold's `Metrics` -- deliberately omits
    `equity_curve`/`closed_trades` (the two genuinely large fields) from
    what gets persisted to `runs/experiments.jsonl`. The full `Metrics`
    (including both) stays available in the in-memory `WalkForwardResult`
    for any caller that needs it (e.g. Task D's grid search comparing
    candidates); the persisted log only needs the numbers CLAUDE.md's
    Eligibility Bar is expressed in terms of.

    `return_skewness`/`return_kurtosis`/`num_returns` (Strategy Research
    Task Q) are logged **unconditionally**, departing from the recent
    "field only appears when the feature is actually used" convention
    below (`parameter_sensitivity`, `funding_pnl_included`). Justified
    because they are always computable and the Probabilistic/Deflated
    Sharpe Ratio needs them for every run: gating them behind a flag would
    be pure ceremony, and dropping `equity_curve` (above) means a logged
    record could otherwise never be re-evaluated under PSR/DSR without
    re-running the entire backtest. Flagged as a judgment call in
    `.planning/sr-q-deflated-sharpe.md`.
    """
    return {
        "starting_equity": metrics.starting_equity,
        "final_equity": metrics.final_equity,
        "total_return": metrics.total_return,
        "sharpe_ratio": metrics.sharpe_ratio,
        "max_drawdown": metrics.max_drawdown,
        "win_rate": metrics.win_rate,
        "num_trades": metrics.num_trades,
        "profit_factor": metrics.profit_factor,
        "return_skewness": metrics.return_skewness,
        "return_kurtosis": metrics.return_kurtosis,
        "num_returns": metrics.num_returns,
    }


def _fold_result_to_log_dict(fold_result: FoldResult) -> dict:
    record = {
        "fold_index": fold_result.fold_index,
        "train_start_index": fold_result.train_start_index,
        "train_end_index": fold_result.train_end_index,
        "validate_start_index": fold_result.validate_start_index,
        "validate_end_index": fold_result.validate_end_index,
        "metrics": _metrics_summary(fold_result.metrics),
    }
    # Additive -- only present when a caller opted in via
    # run_walk_forward's sensitivity_extractor parameter, so an existing
    # reader of runs/experiments.jsonl sees byte-for-byte the same fold
    # record shape as before this field existed. See run_walk_forward's
    # docstring and .planning/sr-g-overfitting-safeguards.md ("Finding 2").
    if fold_result.parameter_sensitivity is not None:
        record["parameter_sensitivity"] = fold_result.parameter_sensitivity
    return record


def _aggregate_metrics(fold_results: list[FoldResult]) -> dict:
    """Reduce per-fold `Metrics` to the aggregate figures CLAUDE.md's
    Eligibility Bar is evaluated against later -- evaluating the bar
    itself is explicitly not this function's job (see module docstring).

    `None`-not-zero-not-inf propagation matches `metrics.metrics`'s own
    degenerate-input philosophy throughout: a fold with a `None` Sharpe
    (zero trades or zero-variance returns) is excluded from `mean_sharpe`/
    `min_sharpe` (no evidence to average in) but *does* count against
    `all_folds_positive_sharpe` (a `None` fold trivially fails "positive
    in every fold"). Same pattern for `profit_factor`.
    """
    fold_count = len(fold_results)
    if fold_count == 0:
        return {
            "fold_count": 0,
            "mean_sharpe": None,
            "min_sharpe": None,
            "all_folds_positive_sharpe": False,
            "worst_fold_max_drawdown": None,
            "mean_total_return": None,
            "total_trades": 0,
            "mean_profit_factor": None,
            "min_profit_factor": None,
            "folds_with_zero_trades": 0,
        }

    sharpe_values = [fr.metrics.sharpe_ratio for fr in fold_results]
    defined_sharpe_values = [s for s in sharpe_values if s is not None]
    profit_factors = [fr.metrics.profit_factor for fr in fold_results]
    defined_profit_factors = [p for p in profit_factors if p is not None]

    return {
        "fold_count": fold_count,
        "mean_sharpe": (sum(defined_sharpe_values) / len(defined_sharpe_values)) if defined_sharpe_values else None,
        "min_sharpe": min(defined_sharpe_values) if defined_sharpe_values else None,
        "all_folds_positive_sharpe": all(s is not None and s > 0 for s in sharpe_values),
        "worst_fold_max_drawdown": max(fr.metrics.max_drawdown for fr in fold_results),
        "mean_total_return": sum((fr.metrics.total_return for fr in fold_results), Decimal(0)) / fold_count,
        "total_trades": sum(fr.metrics.num_trades for fr in fold_results),
        "mean_profit_factor": (
            (sum(defined_profit_factors) / len(defined_profit_factors)) if defined_profit_factors else None
        ),
        "min_profit_factor": min(defined_profit_factors) if defined_profit_factors else None,
        "folds_with_zero_trades": sum(1 for fr in fold_results if fr.metrics.num_trades == 0),
    }
